-- MySQL Script generated by MySQL Workbench
-- 09/13/17 16:03:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Conselheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conselheiro` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(50) NULL,
  `Telefone` VARCHAR(15) NULL,
  `Celular` VARCHAR(15) NULL,
  `Login` VARCHAR(25) NULL,
  `Senha` VARCHAR(25) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direitos` (
  `ID` INT NOT NULL,
  `Numero` VARCHAR(10) NULL,
  `Descrição` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requerente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NULL,
  `Telefone1` VARCHAR(15) NULL,
  `Telefone2` VARCHAR(15) NULL,
  `Celular` VARCHAR(15) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Numero` VARCHAR(10) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(20) NULL,
  `Estado` VARCHAR(15) NULL,
  `EstadoCivil` VARCHAR(15) NULL,
  `Observação` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
